* hel-org

The [[https://github.com/anuvyklack/hel][Hel]] extension that integrates it with [[https://orgmode.org/][Org-mode]].

** Install

#+begin_src emacs-lisp
(use-package hel-org
  :vc (:url "https://github.com/anuvyklack/hel-org.git" :rev "main")
  :after org)
#+end_src

** Keybindings
*** Navigation

=h=, =j=, =k=, =l= keys with =M-=, =S-M-=, =C-S-= modifiers work as arrows with the same
modifiers except for =J= and =K=, because =J= is occupied in Hel for ~hel-join-line~.

- =g h= ::
  First non-blank. In headlines jumps to text start (after stars and =TODO=
  keyword); pressing again goes to line start. Same smart behavior in list
  items.

- =[ RET= / =] RET= ::
  Insert heading, list item, or table row *above* / *below* current one.

- =[ s= / =] s= or =[ .= / =] .= :: Jump to *previous* / *next* sentence.

*** Org AST navigation

The same as tree-sitter AST climbing commands but for Org-mode:

| Key        | Description                                     |
|------------+-------------------------------------------------|
| =C-h= or =M-o= | Expand region to the nearest enclosing element. |
| =C-l= or =M-i= | Contract region to its first child element.     |
| =C-j= or =M-n= | Move region to the next sibling element.        |
| =C-k= or =M-p= | Move region to the previous sibling element.    |

*** Hel native commands

Hel native commands become org-aware (=d=, =p=, =<=, =>=, ~=~, etc).

Hel's select (=mi=, =ma=) and surround (=ms=, =md=, =mr=) operations work with all Org
emphasis delimiters:

| Char | Markup        |
|------+---------------|
| =*=    | *bold*          |
| =/=    | /italic/        |
| =_=    | _underline_     |
| =+=    | +strikethrough+ |
| ===    | =verbatim=      |
| =~=    | ~code~          |

When =hel-multiple-cursors-mode= is active, the =org-hide-emphasis-markers= is
temporarily set to =nil= so fake cursors can see raw markup delimiters.

*** Date picker (=org-read-date=)

| Key       | Action |
|-----------+--------|
| =M-h= / =M-l= | day    |
| =M-j= / =M-k= | week   |
| =M-H= / =M-L= | month  |
| =M-J= / =M-K= | year   |

*** org-src (source block editing)

Standard conventions for source-block, capture, and table-formula editing
buffers, borrowed from Evil, following Vim convention:

- =Z Z= :: save and exit (Emacs native =C-c C-c=)
- =Z Q= :: Abort, discard changes (Emacs native =C-c C-k=)
